import { StrictMode } from "react";
import { createRoot } from "react-dom/client";
import "./index.css";
import App from "./App.jsx";

createRoot(document.getElementById("root")).render(
  <StrictMode>
    <App />
  </StrictMode>
);

// GANDA: {
//   GEN: "Olubereberye",
//   EXO: "Okuva",
//   LEV: "Ebyabaleevi",
//   NUM: "Okubala",
//   DEU: "Ekyamateeka Olwokubiri",
//   JOS: "Yoswa",
//   JDG: "Balam",
//   RUT: "Luusi",
//   "1SA": "1 Samwiri",
//   "2SA": "2 Samwiri",
//   "1KI": "1 Bassekabaka",
//   "2KI": "2 Bassekabaka",
//   "1CH": "1 Ebyomumirembe",
//   "2CH": "2 Ebyomumirembe",
//   EZR: "Ezera",
//   NEH: "Nekkemiya",
//   EST: "Eseza",
//   JOB: "Yobu",
//   PSA: "Zabbuli",
//   PRO: "Engero",
//   ECC: "Omubuulizi",
//   SNG: "Oluyimba",
//   ISA: "Isaaya",
//   JER: "Yeremiya",
//   LAM: "Okukungubaga",
//   EZK: "Ezeekyeri",
//   DAN: "Danyeri",
//   HOS: "Koseya",
//   JOEL: "Yoweeri",
//   AMO: "Amosi",
//   OBA: "Obadiya",
//   JON: "Yona",
//   MIC: "Mikka",
//   NAH: "Nakum",
//   HAB: "Kaabakuuku",
//   ZEP: "Zeffaniya",
//   HAG: "Kaggayi",
//   ZEC: "Zekkaliya",
//   MAL: "Malaki",
//   MAT: "Matayo",
//   MRK: "Makko",
//   LUK: "Lukka",
//   JHN: "Yokaana",
//   ACT: "Ebikolwa byʼAbatume",
//   ROM: "Abaruumi",
//   "1CO": "1 Abakkolinso",
//   "2CO": "2 Abakkolinso",
//   GAL: "Abaggalatiya",
//   EPH: "Ephesians",
//   PHP: "Abaefeso",
//   COL: "Abakkolosaayi",
//   "1TH": "1 Basessaloniika",
//   "2TH": "2 Basessaloniika",
//   "1TI": "1 Timoseewo",
//   "2TI": "2 Timoseewo",
//   TIT: "Tito",
//   PHM: "Firemooni",
//   HEB: "Abaebbulaniya",
//   JAM: "Yakobo",
//   "1PE": "1 Peetero",
//   "2PE": "2 Peetero",
//   "1JN": "1 Yokaana",
//   "2JN": "2 Yokaana",
//   "3JN": "3 Yokaana",
//   JUD: "Yuda",
//   REV: "Okubikkulirwa",
// },
